### ISSUE TITLE
Service broker can be configured to create space identity on provision

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur-service-broker#103]
To reduce the dependency of the service broker on the Conjur master during deploy time, we are adding a configurable option for apps to authenticate with a space-level identity instead of the default identity that gets created during bind using the binding ID.

This space Host should be created during the provisioning step. It should be created within the policy for the corresponding space (which is loaded during the provision step). The API key for the Host should be stored in a Conjur Variable that should also be created under the space policy.

If at any point during provision the process fails (for example, the space host is created but its API key is not successfully saved), then provision should fail and return an appropriate server error.

**Comment by izgeri** [comment]
@jtuttle @micahlee I added @RafiS3's note about failing the provision if the full process is unable to complete - before we call this issue `Defined` can you please decide the following and add more details to the issue to describe what exactly will be implemented:
- what the expected service broker response to a failed provision should be (does it roll back the actions it took? how does it know whether to delete the space policy it loaded?)
- what HTML error code / message the provision request should return
- what errors should be logged in the service broker app so that it's clear to the end user trying to troubleshoot what went wrong

**Comment by jtuttle** [comment]
- I don't think we need to roll back the org / space policy stuff. It's idempotent and won't do any harm if left in place.
- Seems like a 500 to me since it's not due to any input from the user.
- We have an existing `OrgPolicyNotFound` error that just gets raised and printed into the application logs when the provision fails. For consistency I would suggest we handle this error the same way.

**Comment by jtuttle** [comment]
This feature will be v5-only since we do not support the space / org layers in v4.

Also, the space host will not be deleted on deprovision.

**Comment by jtuttle** [comment]
@izgeri regarding your above comments, I found it easiest to roll this into the functionality that creates the org and space policies, so it will share the same error handling, response codes, etc. I think this is probably fine as it's actually a fairly low-impact change but let me know if you disagree.

**Comment by izgeri** [comment]
> The API key for the Host should be stored in a Conjur Variable that should also be created under the space policy

## CredHub Alternative
We could also consider storing the API key in CredHub, which would have the added benefit of keeping the API key out of VCAP_SERVICES in the app env.

### Potential workflow:

On provision:
- the SB creates a space host in Conjur
- the SB parses the space host API key
- the SB adds the space host API key to credhub with a predictable path related to the space GUID

On bind:
- the SB updates the access control on the space host API key in credhub so the app can access it
- the SB passes the app a reference to the space host API key in CH (instead of an actual API key)

On app start (we hope - TBD):
- diego replaces the CH references with values in the app env
- the conjur buildpack is invoked and uses the process VCAP_SERVICES values to retrieve secrets as usual
