### ISSUE TITLE
Broken master build is fixed

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur-service-broker#178]
At current, the master build is failing. This needs to be investigated and fixed.

**Comment by izgeri** [comment]
there is a branch to work on this fix: `178-broken-master-build`

it's green up to the tests, but the [tests are failing](https://jenkins.conjur.net/job/cyberark--conjur-service-broker/job/178-broken-master-build/2/) and it will require updating how we handle request and response `content-type`s before we can merge these fixes.

**Comment by BradleyBoutcher** [comment]
Fixed in this PR: https://github.com/cyberark/conjur-service-broker/pull/186

It should be noted that, for the time being, version `3.12.6` of puma is *NOT* supported. Although it is specified as the only fix for the security issue Puma is facing, this is incorrect. `3.12.5` is also a qualified fix, and `.6` breaks our existing test framework.
